BEGIN;
ALTER TABLE pos_products ADD COLUMN "requiresExpiry" boolean NOT NULL DEFAULT false;
CREATE TABLE purchases(id text PRIMARY KEY,"supplierId" text NOT NULL REFERENCES suppliers(id),"supplierName" text NOT NULL,reference text,"receivedAt" timestamp NOT NULL DEFAULT now(),subtotal numeric(12,2) NOT NULL CHECK(subtotal>=0),freight numeric(12,2) NOT NULL CHECK(freight>=0),discount numeric(12,2) NOT NULL CHECK(discount>=0),total numeric(12,2) NOT NULL CHECK(total>=0 AND total=subtotal+freight-discount),"registeredBy" text NOT NULL,notes text,UNIQUE("supplierId",reference));
ALTER TABLE expenses ADD COLUMN "sourcePurchaseId" text UNIQUE REFERENCES purchases(id);
CREATE TABLE purchase_items(id text PRIMARY KEY,"purchaseId" text NOT NULL REFERENCES purchases(id) ON DELETE CASCADE,"productId" text NOT NULL REFERENCES pos_products(id),"productName" text NOT NULL,unit text NOT NULL,packaging text NOT NULL,factor numeric(12,3) NOT NULL CHECK(factor>0),"acceptedPackages" int NOT NULL CHECK("acceptedPackages">=0),"refusedPackages" int NOT NULL CHECK("refusedPackages">=0),quantity numeric(12,3) NOT NULL CHECK(quantity>=0 AND quantity=factor*"acceptedPackages"),"packagePrice" numeric(12,2) NOT NULL CHECK("packagePrice">=0),"goodsTotal" numeric(12,2) NOT NULL CHECK("goodsTotal">=0),"totalCost" numeric(12,2) NOT NULL CHECK("totalCost">=0));
CREATE TABLE stock_lots(id text PRIMARY KEY,"recordVersion" int NOT NULL DEFAULT 0,"productId" text NOT NULL REFERENCES pos_products(id),"purchaseItemId" text UNIQUE REFERENCES purchase_items(id),code text NOT NULL,"expiresAt" date,status text NOT NULL DEFAULT 'active' CHECK(status IN ('active','blocked','unverified')),origin text NOT NULL,quantity numeric(12,3) NOT NULL CHECK(quantity>=0),"receivedQuantity" numeric(12,3) NOT NULL CHECK("receivedQuantity">=0),"remainingValue" numeric(12,2) NOT NULL CHECK("remainingValue">=0 AND (quantity>0 OR "remainingValue"=0)),"unitCost" numeric(18,6) NOT NULL CHECK("unitCost">=0),"costEstimated" boolean NOT NULL DEFAULT false,"receivedAt" timestamp NOT NULL DEFAULT now(),reason text);
CREATE INDEX stock_lots_fefo ON stock_lots("productId",status,"expiresAt");
ALTER TABLE stock_movements ADD COLUMN "originType" text,ADD COLUMN "originId" text,ADD COLUMN "sourceMovementId" text UNIQUE REFERENCES stock_movements(id) DEFERRABLE INITIALLY DEFERRED;
CREATE TABLE stock_movement_lots(id text PRIMARY KEY,"movementId" text NOT NULL REFERENCES stock_movements(id) ON DELETE CASCADE,"lotId" text NOT NULL REFERENCES stock_lots(id),delta numeric(12,3) NOT NULL,value numeric(12,2) NOT NULL);
CREATE TABLE stock_inventories(id text PRIMARY KEY,"recordVersion" int NOT NULL DEFAULT 0,status text NOT NULL DEFAULT 'open' CHECK(status IN ('open','posted','cancelled')),"capturedAt" timestamp NOT NULL DEFAULT now(),"postedAt" timestamp,"createdBy" text NOT NULL,"postedBy" text,reason text NOT NULL);
CREATE UNIQUE INDEX one_open_inventory ON stock_inventories(status) WHERE status='open';
CREATE TABLE stock_inventory_lines(id text PRIMARY KEY,"inventoryId" text NOT NULL REFERENCES stock_inventories(id) ON DELETE CASCADE,"lotId" text NOT NULL REFERENCES stock_lots(id),"productName" text NOT NULL,"expectedQuantity" numeric(12,3) NOT NULL CHECK("expectedQuantity">=0),"unitCost" numeric(18,6) NOT NULL CHECK("unitCost">=0),"countedQuantity" numeric(12,3) CHECK("countedQuantity">=0),delta numeric(12,3),UNIQUE("inventoryId","lotId"));
CREATE TABLE purchase_returns(id text PRIMARY KEY,"recordVersion" int NOT NULL DEFAULT 0,"lotId" text NOT NULL REFERENCES stock_lots(id),quantity numeric(12,3) NOT NULL CHECK(quantity>0),"stockValue" numeric(12,2) NOT NULL CHECK("stockValue">=0),reason text NOT NULL,"createdAt" timestamp NOT NULL DEFAULT now(),"registeredBy" text NOT NULL,status text NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','settled')),resolution text,"agreedValue" numeric(12,2) CHECK("agreedValue">=0),"settledAt" timestamp,"settledBy" text,"settlementNote" text);
-- Existing stock has no reliable lot/expiry: preserve the physical balance, quarantine it.
INSERT INTO stock_lots(id,"productId",code,status,origin,quantity,"receivedQuantity","remainingValue","unitCost","costEstimated",reason)
SELECT 'legacy-'||s.id,s."productId",'ABERTURA-'||s.id,'unverified','legacy',s."currentStock",s."currentStock",round(s."currentStock"*s."averageCost",2),s."averageCost",true,'Saldo anterior: revisar lote e validade antes de vender'
FROM stock_items s JOIN pos_products p ON p.id=s."productId" JOIN product_categories c ON c.id=p."categoryId" WHERE s."currentStock">0 AND NOT c."isRestaurant";
CREATE TRIGGER erp_notify AFTER INSERT OR UPDATE OR DELETE ON purchases FOR EACH STATEMENT EXECUTE FUNCTION erp_sync_notify('purchases');
CREATE TRIGGER erp_notify AFTER INSERT OR UPDATE OR DELETE ON stock_lots FOR EACH STATEMENT EXECUTE FUNCTION erp_sync_notify('stockLots');
CREATE TRIGGER erp_version BEFORE UPDATE ON stock_lots FOR EACH ROW EXECUTE FUNCTION erp_bump_version('recordVersion');
CREATE TRIGGER erp_notify AFTER INSERT OR UPDATE OR DELETE ON stock_inventories FOR EACH STATEMENT EXECUTE FUNCTION erp_sync_notify('stockInventories');
CREATE TRIGGER erp_version BEFORE UPDATE ON stock_inventories FOR EACH ROW EXECUTE FUNCTION erp_bump_version('recordVersion');
CREATE TRIGGER erp_notify AFTER INSERT OR UPDATE OR DELETE ON purchase_returns FOR EACH STATEMENT EXECUTE FUNCTION erp_sync_notify('purchaseReturns');
CREATE TRIGGER erp_version BEFORE UPDATE ON purchase_returns FOR EACH ROW EXECUTE FUNCTION erp_bump_version('recordVersion');
COMMIT;
