"use client"

import { PaymentDialog } from "./payment-fields"
import { getDataConfig } from "@/lib/data/config"
import { useState } from "react"
import { useApp } from "@/lib/app-context"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Textarea } from "@/components/ui/textarea"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { Badge } from "@/components/ui/badge"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Plus, Pencil, Trash2, DollarSign, Calendar, AlertCircle } from "lucide-react"
import type { AccountReceivable } from "@/lib/store"
import { CustomerCombobox } from "@/components/customer-combobox"

export function AccountsReceivableManagement() {
  const {
    accountsReceivable,
    customers,
    transactions,
    addAccountReceivable,
    updateAccountReceivable,
    removeAccountReceivable,
    runOperation, addTransaction,
  } = useApp()
  const [isDialogOpen, setIsDialogOpen] = useState(false)
  const [editingAR, setEditingAR] = useState<AccountReceivable | null>(null)
  const [filterStatus, setFilterStatus] = useState<string>("all")
  const [formErrors, setFormErrors] = useState<Record<string, string>>({})

  const [formData, setFormData] = useState({
    customerName: "",
    customerId: "",
    description: "",
    value: "",
    dueDate: "",
    status: "pendente" as AccountReceivable["status"],
    paymentDate: "",
    notes: ""
  })

  const resetForm = () => {
    setFormData({
      customerName: "",
      customerId: "",
      description: "",
      value: "",
      dueDate: "",
      status: "pendente",
      paymentDate: "",
      notes: ""
    })
    setEditingAR(null)
    setFormErrors({})
  }

  const validateForm = (): boolean => {
    const newErrors: Record<string, string> = {}

    if (!formData.customerId) {
      newErrors.customerId = "Cliente é obrigatório"
    }

    if (!formData.description.trim()) {
      newErrors.description = "Descrição é obrigatória"
    }

    if (!formData.value || parseFloat(formData.value) <= 0) {
      newErrors.value = "Valor deve ser maior que zero"
    }

    if (!formData.dueDate) {
      newErrors.dueDate = "Data de vencimento é obrigatória"
    }

    setFormErrors(newErrors)
    return Object.keys(newErrors).length === 0
  }

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()

    if (!validateForm()) {
      return
    }

    const arData = {
      customerName: formData.customerName,
      customerId: formData.customerId,
      description: formData.description,
      value: parseFloat(formData.value),
      dueDate: formData.dueDate,
      status: formData.status,
      paymentDate: formData.paymentDate || undefined,
      notes: formData.notes || undefined
    }

    try {
      if (editingAR) {
        await updateAccountReceivable(editingAR.id, arData)
      } else {
        await addAccountReceivable({
          id: "", // Will be generated by repository
          ...arData
        } as AccountReceivable)
      }

      setIsDialogOpen(false)
      resetForm()
    } catch (error) {
      console.error("Error saving account receivable:", error)
      setFormErrors({ submit: "Erro ao salvar conta a receber" })
    }
  }

  const handleEdit = (ar: AccountReceivable) => {
    setEditingAR(ar)
    setFormData({
      customerName: ar.customerName,
      customerId: ar.customerId,
      description: ar.description,
      value: ar.value.toString(),
      dueDate: ar.dueDate,
      status: ar.status,
      paymentDate: ar.paymentDate || "",
      notes: ar.notes || ""
    })
    setIsDialogOpen(true)
  }

  const handleCustomerChange = (customerId: string, customerName: string) => {
    setFormData({ ...formData, customerId, customerName })
    if (formErrors.customerId) {
      setFormErrors({ ...formErrors, customerId: "" })
    }
  }

  const handleDelete = async (id: string) => {
    if (confirm("Tem certeza que deseja excluir esta conta a receber?")) {
      await removeAccountReceivable(id)
    }
  }

  const [payingAccount, setPayingAccount] = useState<AccountReceivable | null>(null)
  const handleMarkAsPaid = async (ar: AccountReceivable) => {
    if (["pago", "cancelado"].includes(ar.status)) return
    if (getDataConfig().adapter === "database") { setPayingAccount(ar); return }

    const paymentDate = new Date().toISOString().split("T")[0]

    await updateAccountReceivable(ar.id, {
      status: "pago",
      paymentDate,
    })

    await addTransaction({
      id: `T${String(transactions.length + 1).padStart(3, "0")}`,
      date: paymentDate,
      description: `Recebimento: ${ar.description}`,
      value: ar.value,
      type: "receita",
      refId: ar.id,
      category: ar.category || "Contas a Receber",
      responsible: "sistema",
      notes: ar.customerName,
    })
  }

  const getStatusBadge = (status: AccountReceivable["status"]) => {
    const variants = {
      pendente: "default",
      pago: "default",
      vencido: "destructive",
      cancelado: "secondary"
    } as const

    const labels = {
      pendente: "Pendente",
      pago: "Pago",
      vencido: "Vencido",
      cancelado: "Cancelado"
    }

    return (
      <Badge variant={variants[status]} className={status === "pago" ? "bg-green-500" : ""}>
        {labels[status]}
      </Badge>
    )
  }

  const isOverdue = (ar: AccountReceivable) => {
    if (ar.status === "pago" || ar.status === "cancelado") return false
    return new Date(ar.dueDate) < new Date()
  }

  const filteredAR = accountsReceivable.filter(ar => {
    if (filterStatus === "all") return true
    if (filterStatus === "overdue") return isOverdue(ar)
    return ar.status === filterStatus
  })

  const totalPending = accountsReceivable
    .filter(ar => ar.status === "pendente")
    .reduce((sum, ar) => sum + ar.value, 0)

  const totalOverdue = accountsReceivable
    .filter(ar => isOverdue(ar))
    .reduce((sum, ar) => sum + ar.value, 0)

  const totalReceived = accountsReceivable
    .filter(ar => ar.status === "pago")
    .reduce((sum, ar) => sum + ar.value, 0)

  return (
    <div className="space-y-6">
      {/* Summary Cards */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        <PaymentDialog open={!!payingAccount} onClose={() => setPayingAccount(null)} title={`Receber ${payingAccount?.description || ""} · R$ ${(payingAccount?.installments?.filter(part => ["pendente", "vencido"].includes(part.status)).sort((a, b) => a.installmentNumber - b.installmentNumber)[0]?.value ?? payingAccount?.value ?? 0).toFixed(2)}${payingAccount?.installments?.length ? " — próxima parcela pendente" : ""}`} onConfirm={async (paymentMethod, accountId) => {
        if (!payingAccount) return
        const installment = payingAccount.installments?.filter(part => ["pendente", "vencido"].includes(part.status)).sort((a, b) => a.installmentNumber - b.installmentNumber)[0]
        await runOperation("receive-account", { accountReceivableId: payingAccount.id, installmentId: installment?.id, paymentMethod, accountId })
      }} />
      <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-sm font-medium text-muted-foreground">
              Total Pendente
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">
              R$ {totalPending.toFixed(2)}
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-sm font-medium text-muted-foreground">
              Total Vencido
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-red-600">
              R$ {totalOverdue.toFixed(2)}
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-sm font-medium text-muted-foreground">
              Total Recebido
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-green-600">
              R$ {totalReceived.toFixed(2)}
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Main Table */}
      <Card>
        <CardHeader>
          <div className="flex items-center justify-between">
            <div>
              <CardTitle className="flex items-center gap-2">
                <DollarSign className="h-5 w-5" />
                Contas a Receber
              </CardTitle>
              <CardDescription>
                Gerencie suas contas a receber e acompanhe pagamentos
              </CardDescription>
            </div>
            <Dialog open={isDialogOpen} onOpenChange={(open) => {
              setIsDialogOpen(open)
              if (!open) resetForm()
            }}>
              <DialogTrigger asChild>
                <Button>
                  <Plus className="h-4 w-4 mr-2" />
                  Nova Conta
                </Button>
              </DialogTrigger>
              <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto">
                <DialogHeader>
                  <DialogTitle>
                    {editingAR ? "Editar Conta a Receber" : "Nova Conta a Receber"}
                  </DialogTitle>
                  <DialogDescription>
                    Preencha as informações da conta a receber
                  </DialogDescription>
                </DialogHeader>
                <form onSubmit={handleSubmit} className="space-y-4">
                  <div className="grid grid-cols-2 gap-4">
                    <div className="col-span-2">
                      <Label htmlFor="customer">Cliente *</Label>
                      <CustomerCombobox
                        value={formData.customerId}
                        onChange={handleCustomerChange}
                        allowCreate={true}
                        filterActive={true}
                        error={formErrors.customerId}
                      />
                      {formErrors.customerId && (
                        <p className="text-sm text-red-500 mt-1">{formErrors.customerId}</p>
                      )}
                    </div>
                    <div className="col-span-2">
                      <Label htmlFor="description">Descrição *</Label>
                      <Input
                        id="description"
                        value={formData.description}
                        onChange={(e) => setFormData({ ...formData, description: e.target.value })}
                        className={formErrors.description ? "border-red-500" : ""}
                      />
                      {formErrors.description && (
                        <p className="text-sm text-red-500">{formErrors.description}</p>
                      )}
                    </div>
                    <div>
                      <Label htmlFor="value">Valor *</Label>
                      <Input
                        id="value"
                        type="number"
                        step="0.01"
                        value={formData.value}
                        onChange={(e) => setFormData({ ...formData, value: e.target.value })}
                        className={formErrors.value ? "border-red-500" : ""}
                      />
                      {formErrors.value && (
                        <p className="text-sm text-red-500">{formErrors.value}</p>
                      )}
                    </div>
                    <div>
                      <Label htmlFor="dueDate">Data de Vencimento *</Label>
                      <Input
                        id="dueDate"
                        type="date"
                        value={formData.dueDate}
                        onChange={(e) => setFormData({ ...formData, dueDate: e.target.value })}
                        className={formErrors.dueDate ? "border-red-500" : ""}
                      />
                      {formErrors.dueDate && (
                        <p className="text-sm text-red-500">{formErrors.dueDate}</p>
                      )}
                    </div>
                    <div>
                      <Label htmlFor="status">Status</Label>
                      <Select
                        value={formData.status}
                        onValueChange={(value) => setFormData({ ...formData, status: value as AccountReceivable["status"] })}
                      >
                        <SelectTrigger>
                          <SelectValue />
                        </SelectTrigger>
                        <SelectContent>
                          <SelectItem value="pendente">Pendente</SelectItem>
                          <SelectItem value="pago" disabled>Pago — utilize Receber</SelectItem>
                          <SelectItem value="vencido">Vencido</SelectItem>
                          <SelectItem value="cancelado">Cancelado</SelectItem>
                        </SelectContent>
                      </Select>
                    </div>
                    <div>
                      <Label htmlFor="paymentDate">Data de Pagamento</Label>
                      <Input
                        id="paymentDate"
                        type="date"
                        value={formData.paymentDate}
                        onChange={(e) => setFormData({ ...formData, paymentDate: e.target.value })}
                      />
                    </div>
                    <div className="col-span-2">
                      <Label htmlFor="notes">Observações</Label>
                      <Textarea
                        id="notes"
                        value={formData.notes}
                        onChange={(e) => setFormData({ ...formData, notes: e.target.value })}
                        rows={3}
                      />
                    </div>
                  </div>
                  {formErrors.submit && (
                    <p className="text-sm text-red-500">{formErrors.submit}</p>
                  )}
                  <div className="flex justify-end gap-2">
                    <Button type="button" variant="outline" onClick={() => setIsDialogOpen(false)}>
                      Cancelar
                    </Button>
                    <Button type="submit">
                      {editingAR ? "Salvar" : "Criar"}
                    </Button>
                  </div>
                </form>
              </DialogContent>
            </Dialog>
          </div>
        </CardHeader>
        <CardContent>
          <div className="mb-4">
            <Select value={filterStatus} onValueChange={setFilterStatus}>
              <SelectTrigger className="w-[200px]">
                <SelectValue placeholder="Filtrar por status" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="all">Todos</SelectItem>
                <SelectItem value="pendente">Pendente</SelectItem>
                <SelectItem value="overdue">Vencidos</SelectItem>
                <SelectItem value="pago">Pagos</SelectItem>
                <SelectItem value="cancelado">Cancelados</SelectItem>
              </SelectContent>
            </Select>
          </div>

          {filteredAR.length > 0 ? (
            <div className="border rounded-lg">
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Cliente</TableHead>
                    <TableHead>Descrição</TableHead>
                    <TableHead>Valor</TableHead>
                    <TableHead>Vencimento</TableHead>
                    <TableHead>Status</TableHead>
                    <TableHead className="text-right">Ações</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {filteredAR.map((ar) => (
                    <TableRow key={ar.id} className={isOverdue(ar) ? "bg-red-50" : ""}>
                      <TableCell className="font-medium">
                        <div className="flex items-center gap-2">
                          {isOverdue(ar) && <AlertCircle className="h-4 w-4 text-red-600" />}
                          {ar.customerName}
                        </div>
                      </TableCell>
                      <TableCell>{ar.description}</TableCell>
                      <TableCell>R$ {ar.value.toFixed(2)}</TableCell>
                      <TableCell>
                        <div className="flex items-center gap-1">
                          <Calendar className="h-4 w-4 text-muted-foreground" />
                          {new Date(ar.dueDate).toLocaleDateString("pt-BR")}
                        </div>
                      </TableCell>
                      <TableCell>{getStatusBadge(ar.status)}</TableCell>
                      <TableCell className="text-right">
                        <div className="flex justify-end gap-2">
                          {ar.status === "pendente" && (
                            <Button
                              variant="outline"
                              size="sm"
                              onClick={() => handleMarkAsPaid(ar)}
                            >
                              Marcar como Pago
                            </Button>
                          )}
                          <Button
                            variant="ghost"
                            size="sm"
                            onClick={() => handleEdit(ar)}
                          >
                            <Pencil className="h-4 w-4" />
                          </Button>
                          <Button
                            variant="ghost"
                            size="sm"
                            onClick={() => handleDelete(ar.id)}
                          >
                            <Trash2 className="h-4 w-4" />
                          </Button>
                        </div>
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </div>
          ) : (
            <div className="text-center py-8 text-muted-foreground">
              Nenhuma conta a receber encontrada
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  )
}
