"use client"
import { CnpjLookup } from "./cnpj-lookup"
import { CustomerCombobox } from "./customer-combobox"
import { PermissionGate } from "@/components/permission-gate"

import { useState } from "react"
import { useApp } from "@/lib/app-context"
import { useAuth } from "@/lib/auth-context"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Textarea } from "@/components/ui/textarea"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { Badge } from "@/components/ui/badge"
import { Plus, Pencil, Trash2, Building2 } from "lucide-react"
import type { Supplier } from "@/lib/store"

export function SuppliersManagement() {
  const { customers, suppliers, addSupplier, updateSupplier, removeSupplier, addAuditEntry } = useApp()
  const { username } = useAuth()
  const [isDialogOpen, setIsDialogOpen] = useState(false)
  const [editingSupplier, setEditingSupplier] = useState<Supplier | null>(null)
  const [error, setError] = useState("")
  const [searchTerm, setSearchTerm] = useState("")

  const [formData, setFormData] = useState({
    name: "",
    cnpj: "",
    email: "",
    phone: "",
    address: "",
    paymentTerms: "",
    notes: "",
    active: true
  })

  const resetForm = () => {
    setFormData({
      name: "",
      cnpj: "",
      email: "",
      phone: "",
      address: "",
      paymentTerms: "",
      notes: "",
      active: true
    })
    setEditingSupplier(null)
  }

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    setError("")
    try {

    if (editingSupplier) {
      await updateSupplier(editingSupplier.id, { ...formData, recordVersion: editingSupplier.recordVersion })
      await addAuditEntry({
        user: username || "sistema",
        action: formData.active ? "Fornecedor editado" : "Fornecedor desativado",
        reference: formData.name,
      })
    } else {
      await addSupplier({
        id: "", // Will be generated by repository
        ...formData
      })
      await addAuditEntry({
        user: username || "sistema",
        action: "Fornecedor criado",
        reference: formData.name,
      })
    }

    setIsDialogOpen(false)
    resetForm()
    } catch (failure) { setError(failure instanceof Error ? failure.message : "Não foi possível salvar") }
  }

  const handleEdit = (supplier: Supplier) => {
    setEditingSupplier(supplier)
    setFormData({
      name: supplier.name,
      cnpj: supplier.cnpj || "",
      email: supplier.email || "",
      phone: supplier.phone || "",
      address: supplier.address || "",
      paymentTerms: supplier.paymentTerms || "",
      notes: supplier.notes || "",
      active: supplier.active
    })
    setIsDialogOpen(true)
  }

  const handleDelete = async (id: string, expectedVersion?: number) => {
    const supplier = suppliers.find(s => s.id === id)
    if (!supplier) return

    if (confirm("Inativar este fornecedor? O histórico será preservado.")) {
      await removeSupplier(id, expectedVersion)
      await addAuditEntry({
        user: username || "sistema",
        action: "Fornecedor removido",
        reference: supplier.name,
      })
    }
  }

  const filteredSuppliers = suppliers.filter(s =>
    s.name.toLowerCase().includes(searchTerm.toLowerCase()) ||
    s.cnpj?.toLowerCase().includes(searchTerm.toLowerCase())
  )

  const activeSuppliers = filteredSuppliers.filter(s => s.active)
  const inactiveSuppliers = filteredSuppliers.filter(s => !s.active)

  return (
    <div className="space-y-6">
      <Card>
        <CardHeader>
          <div className="flex items-center justify-between">
            <div>
              <CardTitle className="flex items-center gap-2">
                <Building2 className="h-5 w-5" />
                Gestão de Fornecedores
              </CardTitle>
              <CardDescription>
                Gerencie seus fornecedores e suas informações de contato
              </CardDescription>
            </div>
            <Dialog open={isDialogOpen} onOpenChange={(open) => {
              setIsDialogOpen(open)
              if (!open) resetForm()
            }}>
              <DialogTrigger asChild>
                <Button>
                  <Plus className="h-4 w-4 mr-2" />
                  Novo Fornecedor
                </Button>
              </DialogTrigger>
              <DialogContent mobileTask className="max-w-2xl max-h-[90vh] overflow-y-auto">
                <DialogHeader>
                  <DialogTitle>
                    {editingSupplier ? "Editar Fornecedor" : "Novo Fornecedor"}
                  </DialogTitle>
                  <DialogDescription>
                    Preencha as informações do fornecedor
                  </DialogDescription>
                </DialogHeader>
                <form onSubmit={handleSubmit} className="space-y-4">
              {error && <p role="alert" className="text-destructive">{error}</p>}
                  <div className="grid grid-cols-2 gap-4">
                    <div className="col-span-2">
                      <Label htmlFor="name">Nome *</Label>
                      <Input
                        id="name"
                        value={formData.name}
                        onChange={(e) => setFormData({ ...formData, name: e.target.value })}
                        required
                      />
                    </div>
                    <div>
                      <Label>Reutilizar pessoa / empresa existente</Label><CustomerCombobox purpose="supplier" allowCreate={false} onChange={id => { const person = customers.find(c => c.id === id); if (person) setFormData({ ...formData, name: person.name, cnpj: person.cpfCnpj, email: person.email ?? '', phone: person.phone ?? '', address: person.address ?? '' }) }} />
                      <CnpjLookup document={formData.cnpj} onApply={company => setFormData({ ...formData, name: company.name, cnpj: company.cpfCnpj, email: company.email, phone: company.phone, address: company.address })} />
                      <Label htmlFor="cnpj">CPF / CNPJ (opcional)</Label>
                      <Input
                        id="cnpj"
                        value={formData.cnpj}
                        onChange={(e) => setFormData({ ...formData, cnpj: e.target.value })}
                        placeholder="00.000.000/0000-00"
                      />
                    </div>
                    <div>
                      <Label htmlFor="phone">Telefone</Label>
                      <Input
                        id="phone"
                        value={formData.phone}
                        onChange={(e) => setFormData({ ...formData, phone: e.target.value })}
                        placeholder="(00) 00000-0000"
                      />
                    </div>
                    <div className="col-span-2">
                      <Label htmlFor="email">Email</Label>
                      <Input
                        id="email"
                        type="email"
                        value={formData.email}
                        onChange={(e) => setFormData({ ...formData, email: e.target.value })}
                      />
                    </div>
                    <div className="col-span-2">
                      <Label htmlFor="address">Endereço</Label>
                      <Input
                        id="address"
                        value={formData.address}
                        onChange={(e) => setFormData({ ...formData, address: e.target.value })}
                      />
                    </div>
                    <div className="col-span-2">
                      <Label htmlFor="paymentTerms">Condições de Pagamento</Label>
                      <Input
                        id="paymentTerms"
                        value={formData.paymentTerms}
                        onChange={(e) => setFormData({ ...formData, paymentTerms: e.target.value })}
                        placeholder="Ex: 30 dias, À vista, etc."
                      />
                    </div>
                    <div className="col-span-2">
                      <Label htmlFor="notes">Observações</Label>
                      <Textarea
                        id="notes"
                        value={formData.notes}
                        onChange={(e) => setFormData({ ...formData, notes: e.target.value })}
                        rows={3}
                      />
                    </div>
                    <div className="col-span-2 flex items-center gap-2">
                      <input
                        type="checkbox"
                        id="active"
                        checked={formData.active}
                        onChange={(e) => setFormData({ ...formData, active: e.target.checked })}
                        className="h-4 w-4"
                      />
                      <Label htmlFor="active">Fornecedor ativo</Label>
                    </div>
                  </div>
                  <div className="flex justify-end gap-2">
                    <Button type="button" variant="outline" onClick={() => setIsDialogOpen(false)}>
                      Cancelar
                    </Button>
                    <Button type="submit">
                      {editingSupplier ? "Salvar" : "Criar"}
                    </Button>
                  </div>
                </form>
              </DialogContent>
            </Dialog>
          </div>
        </CardHeader>
        <CardContent>
          <div className="mb-4">
            <Input
              placeholder="Buscar por nome ou CNPJ..."
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
            />
          </div>

          {activeSuppliers.length > 0 && (
            <div className="mb-6">
              <h3 className="text-sm font-semibold mb-2">Fornecedores Ativos ({activeSuppliers.length})</h3>
              <div className="border rounded-lg">
                <Table mobileColumns={["Nome", "CNPJ", "Contato", "Condições", "Ações"]} mobilePreview={["Nome", "Contato"]}>
                  <TableHeader>
                    <TableRow>
                      <TableHead>Nome</TableHead>
                      <TableHead>CNPJ</TableHead>
                      <TableHead>Contato</TableHead>
                      <TableHead>Condições</TableHead>
                      <TableHead className="text-right">Ações</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {activeSuppliers.map((supplier) => (
                      <TableRow key={supplier.id}>
                        <TableCell className="font-medium">{supplier.name}</TableCell>
                        <TableCell>{supplier.cnpj || "-"}</TableCell>
                        <TableCell>
                          <div className="text-sm">
                            {supplier.phone && <div>{supplier.phone}</div>}
                            {supplier.email && <div className="text-muted-foreground">{supplier.email}</div>}
                          </div>
                        </TableCell>
                        <TableCell>{supplier.paymentTerms || "-"}</TableCell>
                        <TableCell className="text-right">
                          <div className="flex justify-end gap-2">
                            <PermissionGate permission="suppliers.edit"><Button
                              variant="ghost"
                              size="sm"
                              onClick={() => handleEdit(supplier)}
                            >
                              <Pencil className="h-4 w-4" />
                            </Button></PermissionGate>
                            <PermissionGate permission="suppliers.delete"><Button
                              variant="ghost"
                              size="sm"
                              onClick={() => handleDelete(supplier.id, supplier.recordVersion)}
                            >
                              <Trash2 className="h-4 w-4" />
                            </Button></PermissionGate>
                          </div>
                        </TableCell>
                      </TableRow>
                    ))}
                  </TableBody>
                </Table>
              </div>
            </div>
          )}

          {inactiveSuppliers.length > 0 && (
            <div>
              <h3 className="text-sm font-semibold mb-2">Fornecedores Inativos ({inactiveSuppliers.length})</h3>
              <div className="border rounded-lg">
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead>Nome</TableHead>
                      <TableHead>CNPJ</TableHead>
                      <TableHead>Contato</TableHead>
                      <TableHead className="text-right">Ações</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {inactiveSuppliers.map((supplier) => (
                      <TableRow key={supplier.id} className="opacity-60">
                        <TableCell className="font-medium">{supplier.name}</TableCell>
                        <TableCell>{supplier.cnpj || "-"}</TableCell>
                        <TableCell>
                          <div className="text-sm">
                            {supplier.phone && <div>{supplier.phone}</div>}
                            {supplier.email && <div className="text-muted-foreground">{supplier.email}</div>}
                          </div>
                        </TableCell>
                        <TableCell className="text-right">
                          <div className="flex justify-end gap-2">
                            <PermissionGate permission="suppliers.edit"><Button
                              variant="ghost"
                              size="sm"
                              onClick={() => handleEdit(supplier)}
                            >
                              <Pencil className="h-4 w-4" />
                            </Button></PermissionGate>
                            <PermissionGate permission="suppliers.delete"><Button
                              variant="ghost"
                              size="sm"
                              onClick={() => handleDelete(supplier.id, supplier.recordVersion)}
                            >
                              <Trash2 className="h-4 w-4" />
                            </Button></PermissionGate>
                          </div>
                        </TableCell>
                      </TableRow>
                    ))}
                  </TableBody>
                </Table>
              </div>
            </div>
          )}

          {filteredSuppliers.length === 0 && (
            <div className="text-center py-8 text-muted-foreground">
              {searchTerm ? "Nenhum fornecedor encontrado" : "Nenhum fornecedor cadastrado"}
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  )
}
